obj-m += nct6687.o

curpwd      := $(shell pwd)
kver        ?= $(shell uname -r)
commitcount := $(shell git rev-list --all --count 2>/dev/null)
commithash  := $(shell git rev-parse --short HEAD 2>/dev/null)
fedoraver   := $(shell sed -n 's/.*Fedora release \([^ ]*\).*/\1/p' /etc/fedora-release 2>/dev/null || echo 0)

kdir := /lib/modules/${kver}/build
srcdir := ${curpwd}/src
objdir := ${curpwd}/build/${kver}

# Detect if the kernel was built with clang/LLVM and use the same compiler.
# Distributions increasingly ship LLVM-built kernels, and a module must be
# compiled by the same toolchain that built the kernel it will load into.
KERNEL_CC := $(shell grep -qs CONFIG_CC_IS_CLANG=y ${kdir}/.config && echo clang)
ifeq ($(KERNEL_CC),clang)
  LLVM_FLAGS := LLVM=1
endif

# Fail early and legibly rather than letting kbuild emit a wall of missing-file
# errors when the headers for the target kernel are not installed.
.PHONY: check check-kdir
check-kdir:
	@if [ ! -d "${kdir}" ]; then \
		echo "error: no kernel build tree at ${kdir}"; \
		echo "       install the headers for ${kver}, or build another kernel with:"; \
		echo "         make kver=\$$(uname -r)"; \
		exit 1; \
	fi

# Build out of tree under build/<kver>/. kbuild still needs a Makefile in the
# object directory to learn which modules to build, so generate a one-line one
# rather than copying the real Makefile and the source. Nothing in the
# repository is written, so a plain `make kver=...` can never leave a second
# copy of nct6687.c behind to be built against by a later kernel.
#
# The per-kernel subdirectory matters: kbuild leaves .o and .cmd files that are
# not reusable across kernel versions, and mixing them produces modules that
# link against the wrong symbols.
objmake := ${objdir}/Makefile
objsrc := ${objdir}/nct6687.c

# kbuild resolves a module's source relative to the object directory, and
# KBUILD_SRC does not redirect that lookup for a single-file out-of-tree module.
# A symlink keeps one source of truth in the repository while giving kbuild the
# layout it expects, so a plain `make kver=...` cannot leave a second copy of
# nct6687.c behind to be built against by a later kernel.
#
# The per-kernel subdirectory matters: kbuild leaves .o and .cmd files that are
# not reusable across kernel versions, and mixing them produces modules that
# link against the wrong symbols.
objmkmake:
	@mkdir -p ${objdir}
	@printf '%s\n' \
		'# Generated by the nct6687d Makefile. Do not edit.' \
		'obj-m += nct6687.o' \
		> ${objmake}
	@ln -sfn ${curpwd}/nct6687.c ${objsrc}

.PHONY: build
build: check-kdir objmkmake
	$(MAKE) -C ${kdir} M=${objdir} $(LLVM_FLAGS) \
		KBUILD_EXTRA_SYMBOLS=$(if $(wildcard ${curpwd}/Module.symvers),${curpwd}/Module.symvers,) \
		modules

install: build
	sudo cp ${objdir}/nct6687.ko /lib/modules/${kver}/kernel/drivers/hwmon/
	sudo depmod
	sudo modprobe nct6687

clean:
	@if [ -d "${kdir}" ]; then \
		for d in ${curpwd}/build/*/; do \
			[ -d "$$d" ] && $(MAKE) -C ${kdir} M=$${d%/} $(LLVM_FLAGS) clean; \
		done; \
	fi
	@rm -rf ${curpwd}/build


akmod/build:
	@if [ $(fedoraver) -gt 40 ]; then \
		echo "Fedora version $(fedoraver) is greater than 40, using dnf5 command"; \
		sudo dnf install -y @development-tools; \
	else \
		sudo dnf group install -y "Development Tools" --skip-unavailable; \
	fi
	sudo dnf install -y rpmdevtools kmodtool
	mkdir -p ${curpwd}/.tmp/nct6687d-1.0.${commitcount}/nct6687d
	cp LICENSE Makefile nct6687.c ${curpwd}/.tmp/nct6687d-1.0.${commitcount}/nct6687d
	cd .tmp && tar -czvf nct6687d-1.0.${commitcount}.tar.gz nct6687d-1.0.${commitcount} && cd -
	mkdir -p ${curpwd}/.tmp/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
	cp ${curpwd}/.tmp/nct6687d-1.0.${commitcount}.tar.gz ${curpwd}/.tmp/rpmbuild/SOURCES/
	echo 'nct6687' | tee ${curpwd}/.tmp/rpmbuild/SOURCES/nct6687.conf
	cp fedora/*.spec ${curpwd}/.tmp/rpmbuild/SPECS/
	sed -i "s/MAKEFILE_PKGVER/${commitcount}/g" ${curpwd}/.tmp/rpmbuild/SPECS/*
	sed -i "s/MAKEFILE_COMMITHASH/${commithash}/g" ${curpwd}/.tmp/rpmbuild/SPECS/*
	rpmbuild -ba --define "_topdir ${curpwd}/.tmp/rpmbuild" ${curpwd}/.tmp/rpmbuild/SPECS/nct6687d.spec
	rpmbuild -ba --define "_topdir ${curpwd}/.tmp/rpmbuild" ${curpwd}/.tmp/rpmbuild/SPECS/nct6687d-kmod.spec
akmod/install: akmod/build
	sudo dnf install ${curpwd}/.tmp/rpmbuild/RPMS/*/*.rpm
akmod/clean:
	sudo dnf remove nct6687d
	rm -rf .tmp
akmod: akmod/install


# DKMS builds in tree: it looks for the resulting .ko in the directory it
# invokes make from, so an out-of-tree object path would leave it unable to
# find the module. The kernel tree, compiler selection and the module itself are
# shared with the `build` target above, so the two paths cannot drift apart in
# the ways that actually break a rebuild.
# Smoke tests: builds the module, checks the load-time contract statically, and
# if run as root on a machine with the chip, exercises a PWM write and readback
# and restores it afterwards. See tests/smoke.sh for what is and is not asserted.
check:
	./tests/smoke.sh $(kver)

dkms/build: check-kdir
	$(MAKE) -C ${kdir} M=${curpwd} $(LLVM_FLAGS) modules

dkms/install:
	rm -rf ${curpwd}/dkms
	mkdir -p ${curpwd}/dkms
	cp ${curpwd}/dkms.conf ${curpwd}/Makefile ${curpwd}/nct6687.c ${curpwd}/README.md ${curpwd}/dkms
	sudo rm -rf /usr/src/nct6687d-1
	sudo cp -rT dkms /usr/src/nct6687d-1
	sudo dkms install nct6687d/1
	sudo modprobe nct6687

dkms/clean:
	sudo dkms remove nct6687d/1 --all
	$(MAKE) clean

debian/changelog: FORCE
	git --no-pager log \
		--format='nct6687d-dkms (%ad) unstable; urgency=low%n%n  * %s%n%n -- %aN <%aE>  %aD%n' \
		--date='format:%Y%m%d-%H%M%S' \
		> $@

deb: debian/changelog
	sudo apt install -y debhelper dkms
	@if apt-cache show dh-dkms > /dev/null 2>&1; then \
		sudo apt-get install -y dh-dkms; \
	fi
	dpkg-buildpackage -b -rfakeroot -us -uc

.PHONY: FORCE
FORCE:
